CREATE OR ALTER FUNCTION [dbo].[FN_UserHierarchy_Gorkha]
(
	@TYPE VARCHAR(25) = '%',
	@ID   VARCHAR(25) = '%'
)
RETURNS TABLE
AS
RETURN
(
	WITH UserHierarchy AS
	(
		SELECT A.ID , A.NAME , A.CODE , A.DIVISION , A.TYPE , A.PARENT
		FROM SALESHIERARCHY_MASTER A WITH (NOLOCK)
		WHERE
			A.TYPE = 'USER' AND A.STATUS = 1

		UNION ALL

		SELECT C.ID , C.NAME , C.CODE , C.DIVISION , C.TYPE , C.PARENT
		FROM SALESHIERARCHY_MASTER C WITH (NOLOCK)
		INNER JOIN UserHierarchy U ON C.PARENT = U.ID
		WHERE
			C.STATUS = 1

	)

	SELECT
		DISTINCT U.ID , U.NAME , U.CODE , U.DIVISION , U.TYPE , U.PARENT , D.ACID , D.SOCODE , D.COMPANYID
	FROM UserHierarchy U
	INNER JOIN SALESHIERARCHY_ACLIST D WITH (NOLOCK) ON U.ID = D.SOCODE
	WHERE
		(@TYPE = '%' OR U.TYPE = @TYPE)
		AND (@ID = '%' OR U.CODE = @ID)
);