CREATE OR ALTER     PROCEDURE [dbo].[GBP_CLAIMREPORT_BILLWISEDETAIL]
--Declare
	@DATE1 DATE = NULL,
	@DATE2 DATE = NULL,
	@COMPANYID VARCHAR(255) = '%',
	@ACID VARCHAR(100) = '%'
	,@REPCRITERIA VARCHAR(MAX) OUTPUT,
	@REPORTNAME VARCHAR(MAX) OUTPUT


AS

/*
SELECT @DATE1 = '2025-07-17' , @DATE2 = '2026-07-16' , @COMPANYID = 'cheerstrade', @ACID = '%'
--*/


SET @REPCRITERIA = '@As On Dated : ' + FORMAT(@DATE1, 'MM-dd-yyyy')  + ' - ' + FORMAT(@DATE2, 'MM-dd-yyyy')
SET @REPORTNAME = 'Claim Report - Bill Wise Detail';


DROP TABLE IF EXISTS #COMPSALES

SELECT C.GORKHA_TYPE ExpenseTypeCode , TRIM(A.REFBILL) REFVCHR , A.VCHRNO , A.PARAC , A.TRNDATE , A.TRNTIME , B.MCODE , SUM(B.RealQty) COMPSALESQTY , SUM(AltQty) COMPSALESQTY_ALT , CONVERT(NUMERIC(32,4),IIF(ISNULL(MAU.CONFACTOR,0) = 0 , DP.COMPLEMENTARYRATE , DP.COMPLEMENTARYRATE / MAU.CONFACTOR)) COMPLEMENTARYRATE , CC.nav_name NavName , CC.nav_code NavCode , MI.MCODE ProductCode , MI.DESCA ProductName
,RA.ACNAME INTO #COMPSALES
FROM TRNMAIN A 
JOIN TRNPROD B ON A.VCHRNO = B.VCHRNO
JOIN BATCHPRICE_MASTER BM ON B.MCODE = BM.MCODE AND B.BATCH = BM.BATCHCODE
JOIN DetailPrice DP ON BM.PRICEID = DP.PRICEID AND BM.MCODE= DP.MCODE
JOIN RMD_TRNMAIN_ADDITIONALINFO C ON A.VCHRNO = C.VCHRNO
JOIN MENUITEM MI ON B.MCODE = MI.MCODE
LEFT JOIN RMD_ACLIST RA ON MI.Supplier = RA.ACID
LEFT JOIN MULTIALTUNIT MAU WITH (NOLOCK) ON B.MCODE = MAU.MCODE AND MAU.ALTUNIT = 'CASE'
LEFT JOIN COMPANY CC WITH (NOLOCK) ON A.COMPANYID = CC.COMPANYID
WHERE A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND A.VoucherType = 'TI' AND C.GORKHA_TYPE IN (SELECT TypeCode from TYPE_MASTER)
AND (@COMPANYID = '%' OR A.COMPANYID IN (SELECT * FROM DBO.Split(@COMPANYID,',')))
AND (@ACID = '%' OR RA.ACID IN (SELECT * FROM DBO.Split(@ACID,',')))
GROUP BY C.GORKHA_TYPE , TRIM(A.REFBILL) , A.PARAC , A.VCHRNO , A.TRNDATE , A.TRNTIME , B.MCODE , IIF(ISNULL(MAU.CONFACTOR,0) = 0 , DP.COMPLEMENTARYRATE , DP.COMPLEMENTARYRATE / MAU.CONFACTOR) , CC.nav_name , CC.nav_code , MI.MCODE , MI.DESCA, RA.ACNAME


DROP TABLE IF EXISTS #SALES

SELECT A.VCHRNO , MCODE , SUM(RealQty) SALESQTY ,sum(AltQty) SALESQTY_ALT
INTO #SALES
FROM TRNMAIN A
JOIN TRNPROD B ON A.VCHRNO = B.VCHRNO
WHERE A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND A.VoucherType = 'TI'
AND (@COMPANYID = '%' OR A.COMPANYID IN (SELECT * FROM DBO.Split(@COMPANYID,',')))
AND EXISTS (SELECT * FROM #COMPSALES X WHERE A.VCHRNO = X.REFVCHR)
GROUP BY A.VCHRNO , MCODE


DROP TABLE IF EXISTS #SALESRETURN

SELECT TRIM(A.REFBILL) REFBILL , MCODE , SUM(REALQTY_IN) SALESRETURNQTY ,sum(ALTQTY_IN) SALESRETURNQTY_ALT
INTO #SALESRETURN
FROM TRNMAIN A
JOIN TRNPROD B ON A.VCHRNO = B.VCHRNO
WHERE A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND A.VoucherType = 'CN'
AND (@COMPANYID = '%' OR A.COMPANYID IN (SELECT * FROM DBO.Split(@COMPANYID,',')))
AND EXISTS (SELECT * FROM #COMPSALES X WHERE TRIM(A.REFBILL) = X.VCHRNO)
GROUP BY TRIM(A.REFBILL) , MCODE


SELECT TrnDate, NavCode , NavName , ProductCode , ProductName , PAN , PartyName , RefBillNo , Qty , QtyCase , Type , CompRefNo , CompQty , CompQtyCase , CompRate , CompAmount , [TDS(15%)] , TotalAmount
FROM	(
	SELECT FORMAT(C.TrnDate , 'MM/dd/yyyy') TrnDate, c.NavCode , c.NavName , ProductCode , ProductName , R.VATNO PAN , R.ACNAME PartyName , X.VCHRNO RefBillNo , XX.SALESQTY Qty , XX.SALESQTY_ALT QtyCase , ExpenseTypeCode Type , c.VCHRNO CompRefNo , (c.COMPSALESQTY - ISNULL(YY.SALESRETURNQTY,0))	   CompQty , (c.COMPSALESQTY_ALT - ISNULL(YY.SALESRETURNQTY_ALT,0)) CompQtyCase , C.COMPLEMENTARYRATE CompRate , CAST((c.COMPSALESQTY - ISNULL (YY.SALESRETURNQTY,0))*C.COMPLEMENTARYRATE AS NUMERIC(32,2)) CompAmount , IIF( ExpenseTypeCode = 'AC' , 0 , CAST((((c.COMPSALESQTY - ISNULL  (YY.SALESRETURNQTY,0))*C.COMPLEMENTARYRATE) / 0.85) * 0.15 AS NUMERIC(32,2))) [TDS(15%)] , IIF( ExpenseTypeCode = 'AC' , CAST((c.COMPSALESQTY -	  ISNULL(YY.SALESRETURNQTY,0))*C.COMPLEMENTARYRATE AS NUMERIC(32,2)) ,CAST(((c.COMPSALESQTY - ISNULL(YY.SALESRETURNQTY,0))*C.COMPLEMENTARYRATE)/0.85 AS NUMERIC(32,2))) TotalAmount , 'A' FLG , ISNULL(Q.ORD,99) ORD , TRNTIME , 'R' FFLG
	FROM #COMPSALES C 
	LEFT JOIN (SELECT DISTINCT VCHRNO FROM #SALES) X ON C.REFVCHR = X.VCHRNO
	LEFT JOIN #SALES XX ON X.VCHRNO = XX.VCHRNO AND C.MCODE = XX.MCODE
	LEFT JOIN #SALESRETURN YY ON C.VCHRNO = YY.REFBILL AND C.MCODE = YY.MCODE
	LEFT JOIN RMD_ACLIST R ON C.PARAC = R.ACID
	LEFT JOIN (VALUES ('PP',1),('OP',2),('NEV',3)) AS Q (TYP,ORD) ON ExpenseTypeCode = Q.TYP
	
	UNION ALL
	
	SELECT NULL TrnDate, c.NavCode , c.NavName , NULL ProductCode , 'Total >>' ProductName , NULL PAN , NULL PartyName , NULL RefBillNo , SUM   (XX.SALESQTY) Qty , SUM(XX.SALESQTY_ALT) QtyCase , ExpenseTypeCode Type , NULL CompRefNo , SUM(c.COMPSALESQTY - ISNULL(YY.SALESRETURNQTY,0))   CompQty , SUM(c.COMPSALESQTY_ALT - ISNULL(YY.SALESRETURNQTY_ALT,0)) CompQtyCase , NULL CompRate , CAST(SUM((c.COMPSALESQTY - ISNULL   (YY.SALESRETURNQTY,0))*C.COMPLEMENTARYRATE) AS NUMERIC(32,2)) CompAmount , IIF( ExpenseTypeCode = 'AC' , 0 , CAST(SUM((((c.COMPSALESQTY - ISNULL   (YY.SALESRETURNQTY,0))*C.COMPLEMENTARYRATE) / 0.85) * 0.15) AS NUMERIC(32,2))) [TDS(15%)] , IIF( ExpenseTypeCode = 'AC' , CAST(SUM((c. COMPSALESQTY - ISNULL(YY.SALESRETURNQTY,0))*C.COMPLEMENTARYRATE) AS NUMERIC(32,2)) ,CAST(SUM(((c.COMPSALESQTY - ISNULL(YY.SALESRETURNQTY,0)) *C.COMPLEMENTARYRATE)/0.85) AS NUMERIC(32,2))) TotalAmount , 'B' FLG , ISNULL(Q.ORD,99) ORD , NULL TRNTRIME , 'B' FFLG
	FROM #COMPSALES C 
	LEFT JOIN (SELECT DISTINCT VCHRNO FROM #SALES) X ON C.REFVCHR = X.VCHRNO
	LEFT JOIN #SALES XX ON X.VCHRNO = XX.VCHRNO AND C.MCODE = XX.MCODE
	LEFT JOIN #SALESRETURN YY ON C.VCHRNO = YY.REFBILL AND C.MCODE = YY.MCODE
	LEFT JOIN RMD_ACLIST R ON C.PARAC = R.ACID
	LEFT JOIN (VALUES ('PP',1),('OP',2),('NEV',3)) AS Q (TYP,ORD) ON ExpenseTypeCode = Q.TYP
	GROUP BY c.navcode , c.navname , ExpenseTypeCode , ISNULL(Q.ORD,99)
) A
ORDER BY ORD , Type , NavName , FLG , PartyName , TRNDATE , TRNTIME , ProductName

SELECT NULL