CREATE OR ALTER       PROCEDURE [dbo].[GBP_secondaryStockReportforClaim_custom]
--DECLARE
@DATE1 DATE,
@DATE2 DATE,
@COMPANYID VARCHAR(50) = '%',
@MCODE VARCHAR(50) = '%',
@SHOWBATCHWISE BIT = 0,
@PCL VARCHAR(25) = 'PC007',
@PHISCALID VARCHAR(10) = '82/83',
@ACID VARCHAR(100) = '%'
,@REPCRITERIA VARCHAR(MAX) OUTPUT,
@REPORTNAME VARCHAR(MAX) OUTPUT

AS

--select @DATE1 = '2025-11-01' , @DATE2 = '2025-11-06' , @COMPANYID = '%' , @ACID = '%'
/*SELECT @DATE1 = BEGINDATE FROM PhiscalYear WHERE PhiscalID = @PHISCALID*/

SET @REPORTNAME = 'Claim Report - Stock Summary'
SET @REPCRITERIA = 'Date Range From : '+FORMAT(@DATE1,'MM-dd-yyyy')+' - '+FORMAT(@DATE2,'MM-dd-yyyy')


DROP TABLE IF EXISTS #RAWdATA

SELECT
	A.COMPANYID , B.MCODE , BATCH , 
	SUM(IIF(A.VoucherType = 'OP' OR A.TRNDATE < @DATE1 , (REALQTY_IN - REALQTY) , 0)) openingQty,
	SUM(IIF(A.VoucherType IN ('PI','DN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 , (REALQTY_IN - REALQTY) , 0)) purchaseQty,
	SUM(IIF(A.VoucherType IN ('TI','CN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND ISNULL(GORKHA_TYPE , '') = 'OP' , (REALQTY - REALQTY_IN) , 0)) OPSalesQty,
	SUM(IIF(A.VoucherType IN ('TI','CN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND ISNULL(GORKHA_TYPE , '') = 'PP', (REALQTY - REALQTY_IN) , 0)) PPSalesQty,
	SUM(IIF(A.VoucherType IN ('TI','CN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND ISNULL(GORKHA_TYPE , '') = 'NEV', (REALQTY - REALQTY_IN) , 0)) NEVSalesQty,
	SUM(IIF(A.VoucherType IN ('TI','CN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND ISNULL(GORKHA_TYPE , '') = 'AC', (REALQTY - REALQTY_IN) , 0)) ACSalesQty,
	SUM(IIF(A.VoucherType IN ('TI','CN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND ISNULL(GORKHA_TYPE , '') = 'BC', (REALQTY - REALQTY_IN) , 0)) BCSalesQty,
	SUM(IIF(A.VoucherType IN ('TI','CN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND ISNULL(GORKHA_TYPE , '') = 'TVB', (REALQTY - REALQTY_IN) , 0)) TVBSalesQty,
	SUM(IIF(A.VoucherType IN ('TI','CN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND ISNULL(GORKHA_TYPE , '') = 'TEX', (REALQTY - REALQTY_IN) , 0)) TEXSalesQty,
	SUM(IIF(A.VoucherType IN ('TI','CN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 AND ISNULL(GORKHA_TYPE , '') NOT IN ('PP','OP','NEV','TVB','TEX','BC','AC') , (REALQTY - REALQTY_IN) , 0)) OtherSalesQty,
	SUM(IIF(A.VoucherType IN ('TI','CN') AND A.TRNDATE BETWEEN @DATE1 AND @DATE2 , (REALQTY - REALQTY_IN) , 0)) TotalSalesQty,
	SUM(REALQTY_IN - REALQTY) closingQty
INTO #RAWdATA
FROM RMD_TRNMAIN A
JOIN RMD_TRNPROD B ON A.VCHRNO = B.VCHRNO AND A.COMPANYID = B.COMPANYID
LEFT JOIN RMD_TRNMAIN_ADDITIONALINFO C ON A.VCHRNO = C.VCHRNO AND A.COMPANYID = C.COMPANYID
JOIN MENUITEM MI ON B.MCODE = MI.MCODE
LEFT JOIN COMPANY CC WITH (NOLOCK) ON A.COMPANYID = CC.COMPANYID
WHERE TRNDATE <= @DATE2 AND A.PhiscalID = @PHISCALID
AND (@PCL = '%' OR A.PCL = @PCL)
AND (@COMPANYID = '%' OR A.COMPANYID IN (SELECT * FROM DBO.Split(@COMPANYID,',')))
GROUP BY A.COMPANYID , B.MCODE , BATCH

DROP TABLE IF EXISTS #RESULT

SELECT 
	M.MCODE productCode , M.DESCA productName , ISNULL(D.nav_name,'') NavName , ISNULL(D.nav_code,'') NavCode , D.Name [DistributorName],D.CompanyId [DistributorCode],ISNULL(D.ADDRESS2,'') Region,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , openingQty/MAU.CONFACTOR)) openingQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , purchaseQty/MAU.CONFACTOR)) purchaseQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , PPsalesQty/MAU.CONFACTOR)) PPsalesQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , OPsalesQty/MAU.CONFACTOR)) OPsalesQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , NEVSalesQty/MAU.CONFACTOR)) NEVSalesQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , ACSalesQty/MAU.CONFACTOR)) ACSalesQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , BCSalesQty/MAU.CONFACTOR)) BCSalesQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , TVBSalesQty/MAU.CONFACTOR)) TVBSalesQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , TEXSalesQty/MAU.CONFACTOR)) TEXSalesQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , OtherSalesQty/MAU.CONFACTOR)) OthersalesQty ,
	SUM(IIF(ISNULL(MAU.CONFACTOR,0) = 0 , 0 , closingQty/MAU.CONFACTOR)) closingQty 
INTO #RESULT
FROM #RAWdATA A
JOIN MENUITEM M ON A.MCODE = M.MCODE
JOIN BATCHPRICE_MASTER B ON A.MCODE = B.MCODE AND A.BATCH = B.BATCHCODE
LEFT JOIN MULTIALTUNIT MAU ON A.MCODE = MAU.MCODE AND MAU.ALTUNIT = 'Case'
LEFT JOIN RMD_ACLIST C ON A.COMPANYID = C.CUSTOMERID
LEFT JOIN RMD_ACLIST CC ON M.Supplier = CC.ACID
LEFT JOIN COMPANY D ON A.COMPANYID = D.COMPANYID
WHERE
	(@PCL = '%' OR M.PCL = @PCL)
	--AND (@ACID = '%' OR CC.ACID = @ACID)
	AND (@ACID = '%' OR CC.ACID IN (SELECT * FROM DBO.Split(@ACID,',')))
GROUP BY M.MCODE , M.DESCA, D.nav_name , D.nav_code , D.Name,D.CompanyId,ISNULL(D.ADDRESS2,'') 
--SELECT * FROM #RESULT


select 
	Navcode, NavName,[DistributorName],[DistributorCode],Region, productCode , productName ,
	CONVERT(NUMERIC(32,2),openingQty) opening ,
	CONVERT(NUMERIC(32,2),purchaseQty) purchase ,
	CONVERT(NUMERIC(32,2),OthersalesQty) sales , 
	CONVERT(NUMERIC(32,2),PPsalesQty) PP ,
	CONVERT(NUMERIC(32,2),OPsalesQty) OP ,
	CONVERT(NUMERIC(32,2),NEVSalesQty) NEV ,
	CONVERT(NUMERIC(32,2),ACSalesQty) AC ,
	CONVERT(NUMERIC(32,2),BCSalesQty) BC ,
	CONVERT(NUMERIC(32,2),TVBSalesQty) TVB ,
	CONVERT(NUMERIC(32,2),TEXSalesQty) TEX ,
	CONVERT(NUMERIC(32,2),closingQty) closing
from #RESULT
ORDER BY productName

select 
	'Total' productName , 
	CONVERT(NUMERIC(32,2),SUM(openingQty)) opening ,
	CONVERT(NUMERIC(32,2),SUM(purchaseQty)) purchase ,
	CONVERT(NUMERIC(32,2),SUM(OthersalesQty)) sales , 
	CONVERT(NUMERIC(32,2),SUM(PPsalesQty)) PP ,
	CONVERT(NUMERIC(32,2),SUM(OPsalesQty)) OP ,
	CONVERT(NUMERIC(32,2),SUM(NEVSalesQty)) NEV ,
	CONVERT(NUMERIC(32,2),SUM(ACSalesQty)) AC ,
	CONVERT(NUMERIC(32,2),SUM(BCSalesQty)) BC ,
	CONVERT(NUMERIC(32,2),SUM(TVBSalesQty)) TVB ,
	CONVERT(NUMERIC(32,2),SUM(TEXSalesQty)) TEX ,
	CONVERT(NUMERIC(32,2),SUM(closingQty)) closing
from #RESULT